// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_Contact();
RcppExport SEXP _rcpp_module_boot_CustomDistribution();
RcppExport SEXP _rcpp_module_boot_DiscreteExponentialDistribution();
RcppExport SEXP _rcpp_module_boot_DiscreteGammaDistribution();
RcppExport SEXP _rcpp_module_boot_simulation();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_Contact", (DL_FUNC) &_rcpp_module_boot_Contact, 0},
    {"_rcpp_module_boot_CustomDistribution", (DL_FUNC) &_rcpp_module_boot_CustomDistribution, 0},
    {"_rcpp_module_boot_DiscreteExponentialDistribution", (DL_FUNC) &_rcpp_module_boot_DiscreteExponentialDistribution, 0},
    {"_rcpp_module_boot_DiscreteGammaDistribution", (DL_FUNC) &_rcpp_module_boot_DiscreteGammaDistribution, 0},
    {"_rcpp_module_boot_simulation", (DL_FUNC) &_rcpp_module_boot_simulation, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_discreteModel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
